### ISSUE TITLE
Improve describtion of governmentalAssetNumber, alternateMatchedAvalId and alternateAvalId

### ISSUE THREAD

**Issue by curban111** [Entwicklung-AvaL-Standard/aval-api-spec#36]
There is currently no statement or explanation in the OpenAPI Spec regarding the attributes "gonvernmentalAssetNumber", "alternateMatchedAvalId" and "alternateAvalId".

When and how these attributes are used must be documented.

**Comment by Pascal-Thiel** [comment]
In our documentation  governmentalAssetNumber is translated as "Behördliche Anlagennummer" and governmentalCarrierNumber is translated as "Behördliche Beförderernummer". We send and store those informations in Fields called "entsorger_nr" and "befoerderer_nr". So i believe they are part of the identification within the "Entsorgungsnachweis"-Process. This process might only be critical for dangerous waste. In the original concept we wanted to be able to send those informations to the client.

For alternateMatchedAvalId i found some documentation saying it is only informational with transaction state 10. It might be added to tell the client another aval-matching between both partners would have been better for the transaction. This might be the case when the client sends a transaction regarding transportation of waste A. But the supplier actualy transported waste B. If the alternateMatchedAvalId is provided the client can review his order as soon as the state 10 is send. Without the alternateMatchedAvalId the client has no further information until he spoke with the supplier about the case.

For alternateAvalId i only found some notes that we won´t implement it until further notice. I believe someone got the idea that it should be good to generate an new Matching based on a state 10 Message. The problem is that there must be some more informations for a new matching. If nobody has a good use case for this field we could discuss to drop it.

**Comment by curban111** [comment]
@Pascal-Thiel and @its5 please check in advance the following additions in the description of the following attributes.

- **governmentalAssetNumber**: _The governmental asset number, in german 'Behördliche Anlagennummer', is a crucial part of the german 'Entsorgungsnachweis' process. Use this attribute while exchanging or documenting critical or dangerous waste using AvaL._
- **governmentalCarrierNumber**: _The governmental carrier number, in german 'Behördliche Beförderernummer', is a crucial part of the german 'Entsorgungsnachweis' process. Use this attribute while exchanging or documenting critical or dangerous waste using AvaL._
- **alternateAvalId**: _This attribute is currently not used. It may be removed in one of the next versions._
- **alternateMatchedAvalId**: _Use this attribute if you want to signal to the client in the response (AvaL state 10 only) that there is a better matching for this transaction. For example, the emptying of a container with mixed scrap was agreed upon during matching. However, steel scrap was actually disposed of and a valid matching already exists for this. This is exactly what you pass as “alternateMatchedAvalId”._

**Comment by its5** [comment]
I think this clarification can be used.

**Comment by Pascal-Thiel** [comment]
Yes, i believe the new description are good. Thank you for your efforts!
